### PR TITLE
Fix reference to "main" branch into "master"

### PR DESCRIPTION
**Pull request by GordianLN**
No idea why this guide is set to "main" as default branch, but changing it to master works :)

#### What

What is the reason for this change?

#### Why

Why is this change important?

#### How

How was this change accomplished?

#### Scope

- [ ] significant change to core configuration
- [ ] independent bonus guide
- [ ] simple bug fix

Fixes # (link issue)

#### Test & maintenance

How can the changes be tested? Is there ongoing maintenance effort? If this is a bonus guide: are you willing to update it from time to time?

#### Animated GIF (optional)

Add some snazz if you feel like it :)

### CODE REVIEW

**Comment by twofaktor** [comment]
The new masters branch now are called "main" instead of "master" by default

With "main" the guide works good

**Comment by GordianLN** [comment]
well..... I don't know about you, but me, I couldn't make it work with main.
It errored out.
I changed to master, and lo and behold, it worked...

**Comment by twofaktor** [comment]
> 

 I do not invent anything, my machine 😘

imagen

imagen

**Comment by GordianLN** [comment]
means then that somebody gets master, someone else main, probably worth adding at least a note? I don't personally mind either way, I just know I spent some time on a not working script, until I bothered to search the error message and realized I had to use master 🤔

**Comment by twofaktor** [comment]
> means then that somebody gets master, someone else main, probably worth adding at least a note? I don't personally mind either way, I just know I spent some time on a not working script, until I bothered to search the error message and realized I had to use master 🤔

means simply that MiniBolt instructions are correct and It works fine, you don't need to make modifications if you follow the guide step by step

**Comment by GordianLN** [comment]
eheh this is not even about fixing the guide anymore, it's like you're denying that I got a `master` branch on repository creation, which is the case in my situation.
image
here's what I see when I open my backup repo... am I imagining things, you say? Minibolt guide couldn't work in my case, that led to a small frustration followed by a small research and a small fix. Someone else in my same situation but less geeky would face a larger frustration and possibly utter failure in making this work, that is the point

**Pull request closed without merging**
