### PR TITLE
[UPDATE] Balance of Satoshis bonus guide

### PR DESCRIPTION
**Pull request by HappyBear-btc**
#### What

to update to the latest version and make easier process with variable.

#### Why

make the guide easier to follow.

#### How

updated versions and used variable.

#### Scope

- [ ] significant change to core configuration
- [x] independent bonus guide
- [ ] simple bug fix

### CODE REVIEW

**Review by 1ma — APPROVED** [review]

**Comment by 1ma** [comment]
I'll leave the merge for @twofaktor as I've never used LND/BoS, just in case. But LGTM.

**Comment by twofaktor** [comment]
hi, thanks for your contribution, was this bonus guide tested on a MiniBolt environment and worked fine? Should I add the "Tested on MiniBolt" tag? 

PD: I did some adjustments

**Comment by HappyBear-btc** [comment]
yes I did it and it works great.
Screenshot_7

**Comment by twofaktor** [comment]
ok, let's go to the main! :rocket:

**Comment by HappyBear-btc** [comment]
oops sorry
the line VERSION=$(git tag | sort --version-sort | tail -n 1) should be added as a command and not as example of output.
image

**Comment by twofaktor** [comment]
> oops sorry the line VERSION=$(git tag | sort --version-sort | tail -n 1) should be added as a command and not as example of output. image

good catch, fixed on commit https://github.com/minibolt-guide/minibolt/commit/bcc73f23bd7817e65bce883b1109bd3abba7f3db

**Pull request merged**
